public class emppickradio {
    public string lastname{set;get;}
    public string Firstname{set;get;}
    public string pancard{set;get;}
    public string[]technology{set;get;}
    public string[]gender{set;get;}
    public string[]city{set;get;}
    public string address{set;get;}
    public string permanent_address{set;get;}
    public void save()
    {
        technology=new string[2];
        gender=new string[2];
        city=new string[4];
        
        
        
        
    }
    
    
    
    

}